## The official one

dataset:
  dataroot: ./dataset/ShapeNetViPC-Dataset
  cat: car #cabinet # plane # watercraft # table, couch, chair, lamp
  batch_size: 128
  nThreads: 16

trainer:
  default_root_dir: experiments
  max_epochs: 360
  check_val_every_n_epoch: 5
  

optimizer:
  lr: 0.001