## The official one

dataset:
  dataroot: ./dataset/ShapeNetViPC-Dataset
  cat: watercraft # car #cabinet # plane # watercraft # table, couch, chair, lamp
  batch_size: 128
  nThreads: 16

trainer:
  devices: '1,2,3,4' # or '0,1,2,3'
  strategy: ddp # null
  default_root_dir: experiments
  max_epochs: 360
  check_val_every_n_epoch: 5
  

optimizer:
  lr: 0.001

lr_scheduler:
  gamma: 0.1