## The official one

dataset:
  dataroot: ./dataset/ShapeNetViPC-Dataset
  cat: cabinet
  batch_size: 128
  nThreads: 16

trainer:
  default_root_dir: work_dir
  max_epochs: 160
  check_val_every_n_epoch: 5
  

optimizer:
  lr: 0.001